baseurl = "https://theothercommunication.com/"
languageCode = "en-us"
title = "The Other Communication"
theme = "agency"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) or
    # most longer texts.
    #
    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Shani Herrmann"
    description = "Intercultural Content Strategy"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "shani@theothercommunication.com"


    # Navigation
    [params.navigation]
		brand = "The Other Communication"
        services = "What I Do"
		about = "Philosophy"
        portfolio = "Clients"
        team = "About"
        contact = "Contact"


    # Hero section
    [params.hero]
        # To change the background image of the hero, replace 'header-bg.jpg' in
        # the 'static/img' folder.
        title = "Truly Communicate"
        subtitle = "learn your clients' language"
        buttonText = "Tell me more"


    # Services section
    [params.services]
        title = "From good to great"
        subtitle = "Defining customer needs and appropriate solutions is only a part of the equation: the secret ingredient to excellent customer satisfaction and sales is understanding how your customers think.<br><br>Shani Herrmann, intercultural strategist, can help you see inside your clients' mind.<br><div style='text-align: center;'>![brain](img/mind 200.jpg)</div><br><br>She goes deep, beyond simple translation or local preference (red vs. blue). <br><br>Her goal? True communication with your customer."

		[[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-hand-o-left"
                title = "Know yourself."
                description = "What are your values? What do you believe? Shani will listen and help you distill your answers so that they are clear to your audience."
            [[params.services.row.list]]
                icon = "fa-hand-o-right"
                title = "Know your customer."
                description = "Through user research and interviews, we discover who your happy customers are. Shani analyzes the data to create a mental model that goes deep to describe the values of your customer. She studies cultures - groups with shared experiences<br><br>[**Shared experience:** same country, same company, same profession, same challenge, same cause, same preferences]<br><br>Shared experiences mean **shared values**, and consequently, shared **priorities**, **language** and **behaviors**. Shani can help you uncover and decipher these unwritten rules."

            [[params.services.row.list]]
                icon = "fa-envelope-o"
                title = "Craft the Message."
                description = "Time to strategize. What's your project? A presentation? A website? A relationship? Shani strategizes ways to connect you and your customers. From positionning your message to choosing a favorable structure and convincing style, she'll work with you and your team so you can get understood. Then she helps you find best ways to integrate them into your communication strategy and materials."

    # Portfolio section
    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "They speak their clients' language"
        subtitle = "Case Studies" 

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
    [params.about]
        title = "Roots"
        subtitle = "Ingredients in Shani's Secret Sauce"
        endpoint = "Your<br>Project"

        # The events will be listed from the top to the bottom.
        # All images are stored under 'static/img/about'.
        # Replace them with your own.
        [[params.about.events]]
            img = "1.jpg"
            date = ""
			circletext = "Our<br>mission"
            title = "Connecting People"
            description = "...by helping them deeply understand themselves and the Other.  Because we acquire multiple, unique perspectives when we walk in other people's shoes, and respond differently to each one, creating multiple versions of ourselves. Learning to communicate with Others is an enriching experience for each of us."

        [[params.about.events]]
            img = "Place setting 200.jpg"
            date = ""
            title = "Other Cultures"
            description = "Shani's love for the peoples and cultures of the world comes from her father: originally from Morocco. he is an expatriate who  speaks 4 languages and married someone from another country.<br><br>The apple doesn’t fall far from the tree. Shani is also an expatriate who speaks four languages (English, French, Portuguese and Spanish), married someone from another country,  - and, like her father, has a daughter with a different passport."

        [[params.about.events]]
            img = "montessori cube 200.jpg"
            date = ""
            title = "Montessori"
            description = "Shani attended her grandmother’s Montessori school which promoted the philosophy of letting children unfold naturally and helping them learn to do for themselves. This approach - to give people the space and conditions in which they can grow on their own - has come to define the way I learn. No surprise, then, that I use the same approach with my clients. I create an environment where people can feel at ease, be creative, and most of all, be themselves. Great things can happen in this space: we can put our finger on what is true, what is essential. Like my mother, grandmother and aunts - all teachers - I gain a deep satisfaction from seeing people grow."

        [[params.about.events]]
            img = "globe 200.jpg"
            date = ""
            title = "Living abroad"
            description = "My time abroad has taught me many things. I’ve learned how to adjust to living in a new country, with a new language and culture. I’ve made friends, diverse in their backgrounds but similar in their values.Most importantly, I’ve learned that language alone is not enough to truly understand people. You must understand the values that govern their belief systems, and recognize the manifestations of those values (language being only one)."

    # Team section
    [params.team]
        title = "I am"
        subtitle = ""
        description = "...on a constant search for what is essential - the values that we manifest in so many ways. Finding these grains of truth - what someone considers truly important - requires both intuition and analysis, art and science, right brain and left brain. Understanding someone's values is the key to communicating with them. It's how we connect."

        # All team member's pictures are stored under 'static/img/team'.
        # Replace them with your own too.

        [[params.team.members]]
            img = "shani-portrait.jpg"
            name = "Shani Herrmann"
            position = "Intercultural Strategist"
            social = [
                ["fa-twitter", "#"],
                ["fa-facebook", "#"],
                ["fa-linkedin", "#"]
            ]

    # Client section
    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    [[params.clients]]
        logo = ".jpg"
        link = "#"

    # Contact section
    [params.contact]
        title = "Let's talk."
        subtitle =  "Shani is looking forward to hearing from you at +33 6 41 88 23 40."
        buttonText = "Send"

        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Your Name *"
            warning = "Please enter your name."

        [params.contact.form.email]
            text = "Your Email *"
            warning = "Please enter your email address."

        [params.contact.form.phone]
            text = "Your Phone *"
            warning = "Please enter your phone number."

        [params.contact.form.message]
            text = "Your Message *"
            warning = "Please enter a message."


    # Footer section
    [params.footer]
        copyright = "Published under the Apache License 2.0."

        [[params.footer.social]]
            icon = "fa-twitter"
            link = "#"

        [[params.footer.social]]
            icon = "fa-facebook"
            link = "#"

        [[params.footer.social]]
            icon = "fa-linkedin"
            link = "#"

        [[params.footer.quicklinks]]
            text = "Privacy Policy"
            link = "#"

        [[params.footer.quicklinks]]
            text = "Terms of Use"
            link = "#"

